"""Stamp a release version into every artifact that displays one.

CI runs this right after checkout on tag builds:

    python installer/set_version.py "${GITHUB_REF_NAME#v}"

The dev tree keeps "0.0.1" placeholders; nothing is stamped locally, so
`/api/version` ≠ "0.0.1" is a reliable "this is a CI artifact" signal.

Stamped sites:
  * claude_mnemos/__init__.py        — __version__ (drives /api/version,
                                       update_check, MCP server version)
  * pyproject.toml                   — package metadata
  * installer/windows/mnemos.iss     — installer AppVersion + VersionInfo
  * installer/macos/setup.py         — CFBundleVersion / ShortVersionString
  * .claude-plugin/plugin.json       — plugin manifest
  * installer/pyinstaller/version_info.txt — generated VSVersionInfo
                                       resource for both Windows exes
                                       (consumed by mnemos.spec when present)

Every substitution is count-checked: a refactor that moves a version site
breaks the build loudly instead of shipping a half-stamped artifact.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")

# Mirrors the VersionInfo metadata already shipped in mnemos.iss.
_VS_VERSION_INFO = """\
# Generated by installer/set_version.py — do not edit, not committed.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, 0),
    prodvers=({major}, {minor}, {patch}, 0),
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Yarik'),
        StringStruct('FileDescription', 'claude-mnemos'),
        StringStruct('FileVersion', '{version}.0'),
        StringStruct('InternalName', 'claude-mnemos'),
        StringStruct('LegalCopyright', 'Copyright (c) 2026 Yarik'),
        StringStruct('OriginalFilename', 'claude-mnemos.exe'),
        StringStruct('ProductName', 'claude-mnemos'),
        StringStruct('ProductVersion', '{version}.0'),
      ]),
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def _sub_exactly(path: Path, pattern: str, replacement: str, *, count: int) -> None:
    text = path.read_text(encoding="utf-8")
    new_text, n = re.subn(pattern, replacement, text)
    if n != count:
        raise RuntimeError(
            f"{path}: expected {count} match(es) of {pattern!r}, found {n} — "
            "a version site moved; update installer/set_version.py"
        )
    path.write_text(new_text, encoding="utf-8")


def stamp(root: Path, version: str) -> None:
    if not _VERSION_RE.match(version):
        raise ValueError(f"not a release version: {version!r} (want MAJOR.MINOR.PATCH)")
    major, minor, patch = version.split(".")

    _sub_exactly(
        root / "claude_mnemos" / "__init__.py",
        r'__version__ = "[^"]+"',
        f'__version__ = "{version}"',
        count=1,
    )
    _sub_exactly(
        root / "pyproject.toml",
        r'(?m)^version = "[^"]+"$',
        f'version = "{version}"',
        count=1,
    )
    _sub_exactly(
        root / "installer" / "windows" / "mnemos.iss",
        r'#define MyAppVersion "[^"]+"',
        f'#define MyAppVersion "{version}"',
        count=1,
    )
    _sub_exactly(
        root / "installer" / "macos" / "setup.py",
        r'("CFBundle(?:Version|ShortVersionString)": )"[^"]+"',
        rf'\g<1>"{version}"',
        count=2,
    )
    _sub_exactly(
        root / ".claude-plugin" / "plugin.json",
        r'"version": "[^"]+"',
        f'"version": "{version}"',
        count=1,
    )

    res_path = root / "installer" / "pyinstaller" / "version_info.txt"
    res_path.parent.mkdir(parents=True, exist_ok=True)
    res_path.write_text(
        _VS_VERSION_INFO.format(major=major, minor=minor, patch=patch, version=version),
        encoding="utf-8",
    )


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: python installer/set_version.py X.Y.Z", file=sys.stderr)
        return 2
    root = Path(__file__).resolve().parent.parent
    stamp(root, argv[1])
    print(f"stamped {argv[1]} into version sites under {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
